<?php
    return [
        'email_footer'               => 'Do not reply any email to this email address. This email sent automatically by our system. ',
        'login_message'              => 'กรุณาเข้าสู่ระบบ',
        'text_forgot_password'       => 'ลืมรหัสผ่าน?',
        'page_title_login'           => 'เข้าสู่ระบบ',
        'page_title_forgot'          => 'ลืมรหัสผ่าน',
        'forgot_message'             => 'Enter your email address, to request password',
        "forgot_text_try_again"      => "เข้าสู่ระบบอีกครั้ง ?",
        'text_no_notification'       => "ไม่มีการแจ้งเตือน",
        'text_view_all_notification' => 'ดูทั้งหมด',
        'label_button_profile'       => "โปรไฟล์",
        'filter_dialog_title'        => 'ตัวกรองและจัดเรียงขั้นสูง',
        'there_is_no_option'         => 'There is no any options setting for this inputType',
        'no'                         => 'ไม่',

        'text_enter_the_password'     => 'กรุณาป้อนรหัสผ่านเพื่อเข้าใช้งาน',
        'text_or_sign_in'             => 'หรือเข้าสู่ระบบด้วยบัญชีอื่น',
        'text_default_add_new_module' => 'เพิ่ม :module ใหม่',
        'text_default_list_module'    => 'รายการ :module',
        'text_default_help_password'  => 'ความยาวขั้นต่ำ 5 ตัวอักษร. ปล่อยทิ้งไว้หากคุณไม่ต้องการเปลี่ยนระหัสผ่าน.',
        'text_default_help_upload'    => 'ประเภทไฟล์ที่ใช้งานได้ : JPG, JPEG, PNG, GIF, BMP',
        'text_default_help_number'    => 'สามารถป้อนได้เพียงตัวเลขเท่านั้น',
        'text_default_help_email'     => 'กรุณาป้อนอีเมลที่ถูกต้อง',
        'text_default_help_text'      => 'สามารถป้อนได้เพียงตัวอักษรเท่านั้น',
        'text_default_help_url'       => 'กรุณาป้อน URL',
        'text_dashboard'              => 'หน้าแรก',
        'text_delete'                 => 'ลบ',
        'text_prefix_option'          => 'กรุณาเลือก',
        'text_loading'                => 'กำลังโหลดข้อมูล...',

        'message_after_logout'    => 'ออกจากระบบเรียบร้อยแล้ว!',
        'message_forgot_password' => 'เราได้ส่งรหัสผ่านใหม่ให้ทางอีเมล กรุณาตรวจสอบอีเมลของคุณ !',

        'page_not_found'            => 'ไม่ถบหน้าที่ต้องการ',
        'page_not_found_text'       => 'We are unable search the page that you are looking for.',
        'page_not_found_tips' => '* Please make sure the URL is correct<br/>
                * Please make sure the font capitalizing is correct because case sensitive<br/>
                * Maybe the page that you are looking for has been deleted by Admin<br/>
                * You can go back by click Back Button at browser<br/>',

        'log_try_view'            => 'Try view the data :name at :module',
        'log_try_edit'            => 'Try edit the data :name at :module',
        'log_try_add'             => 'Try add data at :module',
        'log_try_add_save'        => 'Try add the data :name data at :module',
        'log_try_delete'          => 'Try delete the :name data at :module',
        'log_try_delete_selected' => 'Try delete selected at :module',
        'log_try_delete_image'    => 'Try delete the image of :name data at :module',
        'log_try_update'          => 'Try update the :name data at :module',
        'log_add'                 => 'Add New Data :name at :module',
        'log_update'              => 'Update data :name at :module',
        'log_delete'              => 'Delete data :name at :module',
        'log_delete_image'        => 'Delete the image of :name at :module',
        'log_login'               => ':email login with IP Address :ip',
        'log_forgot'              => 'Someone with IP :ip request a password for :email',
        'log_logout'              => ':email logout',

        'alert_delete_selected'         => 'ยืนยันการลบข้อมูลที่เลือกทั้งหมด?',
        'alert_delete_selected_success' => 'ลบรายการที่เลือกแล้ว !',
        'alert_bulk_action_button'      => 'ยืนยันการทำงาน ',
        'alert_action'                  => ':action เรียบร้อยแล้ว!',
        'alert_add_data_success'    => 'เพิ่มข้อมูลเรียบร้อยแล้ว !',
        'alert_add_data_failed'     => 'ไม่สามารถบันทึกข้อมูลได้ !',
        'alert_update_data_success' => 'อัพเดทข้อมูลเรียบร้อยแล้ว!',
        'alert_update_data_failed'  => 'ไม่สามารถอัพเดทข้อมูลได้',
        'alert_delete_data_success' => 'ลบข้อมูลเรียบร้อยแล้ว !',
        'alert_want_to_logout'      => 'ยืนยันการออกจากระบบ ?',
        'alert_warning'             => "เกิดข้อผิดพลาด",
        'alert_danger'              => 'เกิดข้อผิดพลาด ....',
        'alert_success'             => 'สำเร็จ...',
        'alert_info'                => 'Information',
        'alert_primary'             => 'Information',
        'alert_session_expired'     => 'Your session was expired, please login again !',
        'alert_password_wrong'      => 'Sorry your password is wrong !',
        'alert_required'            => 'Please make sure to fill out all the required fields correctly',
        'alert_error_ajax'          => 'Okay, It is embarasing, something went wrong, we will fix it soon !',
        'alert_validation_error'        => 'Please fill out the form correctly : :error',

        'add_data_page_title'    => 'สร้าง :module',
        'edit_data_page_title'   => 'แก้ไข :module',
        'detail_data_page_title' => 'รายละเอียด :module',

        'default_module_description' => 'รายการ',

        'delete_description_confirm' => "คุณจะไม่สามารถนำข้อมูลกลับมาได้!",
        'delete_title_confirm'       => "ยืนยัน ?",


        'action_show_data'       => 'แสดงข้อมูล',
        'action_add_data'        => 'เพิ่มข้อมูล',
        'action_delete_selected' => 'ลบรายการที่เลือก',

        'action_label'       => 'จัดการ',
        'action_detail_data' => 'ดูรายละเอียด',
        'action_edit_data'   => 'แก้ไขข้อมูล',
        'action_delete_data' => 'ลบ',


        'button_cancel'          => 'ยกเลิก',
        'button_add'             => 'เพิ่ม',
        'button_edit'            => 'ลบ',
        'button_back'            => 'กลับ',
        'button_save'            => 'บันทึก',
        'button_save_more'       => 'บันทึกและเพิ่มอีก',
        'button_import'          => 'นำเข้าข้อมูล',
        'button_export'          => 'ส่งออกข้อมูล',
        'button_filter'          => 'ตัวกรองและจัดเรียง',
        'button_close'           => 'ปิด',
        'button_submit'          => 'ยืนยัน',
        'button_logout'          => 'ออกจากระบบ',
        'button_sign_in'         => 'เข้าสู่ระบบ',
        'button_selected_action' => 'จัดการ',
        'button_download_file'   => 'ดาวน์โหลดไฟล์',
        'button_reset'           => 'รีเซ็ท',
        'button_add_to_table'    => 'เพิ่มไปยังตาราง',

        'export_dialog_title'            => "ดาวน์โหลดข้อมูล",
        'export_dialog_filename'         => 'ชื่อไฟล์',
        'export_dialog_help_filename'    => 'คุณสามารถเปลี่ยนชื่อไฟล์ได้ตามต้องการ',
        'export_dialog_maxdata'          => "จำนวนสูงสุด",
        'export_dialog_help_maxdata'     => 'สามารถดาวน์โหลดข้อมูลได้สูงสุด 100,000 ชุด',
        'export_dialog_columns'          => 'คอลัมน์',
        'export_dialog_format_export'    => 'ประเภทไฟล์',
        'export_dialog_show_advanced'    => 'เพิ่มเติม',
        'export_dialog_page_size'        => 'ขนาดกระดาษ',
        'export_dialog_set_default'      => 'กำหนดเป็นขนาดเริ่มต้น',
        'export_dialog_page_orientation' => 'การจัดวาง',

        'import_page_title'         => 'นำเข้าข้อมูล :module',
        'dashboard_default_text'    => 'ยินดีต้อนรับเข้าสู่ระบบ :appname',
        'form_back_to_list'         => 'กลับไปหน้ารายการ :module',
        'not_logged_in'             => 'คุณยังไม่ได้เข้าสู่ระบบ !',
        'menu_navigation'           => "เมนู",
        'table_data_not_found'      => "ไม่มีข้อมูล",
        "notice_delete_file_upload" => "* If you want to upload other file, please first delete the file.",
        "file_broken"               => "Oops looks like File was Broken !. Click Delete and Re-Upload.",


        'denied_access' => 'คุณไม่มีสิทธิ์ในการเข้าถึงข้อมูล!',
        'denied_update' => 'คุณไม่มีสิทธิ์ในการแก้ไขข้อมูล!',
        'denied_create' => 'คุณไม่มีสิทธิ์ในการสร้างข้อมูล!',
        'denied_delete' => 'คุณไม่มีสิทธิ์ในการลบข้อมูล!',

        'user_image'           => 'รูปผู้ใช้',
        'online'               => 'ออนไลน์',
        'controller_route_404' => 'Controller / Route Not Found',
        'home'                 => 'หน้าแรก',
        'Notificactions'       => 'การแจ้งเตือน',
        'Privileges'           => 'Privileges',
        'Privileges_Roles'     => 'จัดการสิทธิ์',
        'Add_New_Privilege'    => 'เพิ่มสิทธิ์ใหม่',
        'List_Privilege'       => 'รากยการสิทธิ์',
        'add_user'             => 'เพิ่มผู้ใช้',
        'List_users'           => 'รายการผู้ใช้',
        'Menu_Management'      => 'จัดการเมนู',
        'Add_New_Setting'      => 'เพิ่มการตั้งค่า',
        'Add_New_Module'       => 'เพิ่มโมดูลใหม่',
        'List_Module'          => 'รายการโมดูล',
        'Add_New_Statistic'    => 'Add New Statistic',
        'List_Statistic'       => 'List Statistic',
        'Add_New_API'          => 'Add New API',
        'API_Generator'        => 'API Generator',
        'Statistic_Builder'    => 'Statistic Builder',
        'Module_Generator'     => 'สร้างโมดูล',
        'settings'             => 'ตั้งค่า',
        'Users_Management'     => 'จัดการผู้ใช้',
        'list_API'             => 'List API (Documentation)',
        'Generate_Screet_Key'  => 'Generate Secret Key',
        'Add_New_Email'        => 'Add New Email',
        'List_Email_Template'  => 'List Email Template',
        'Email_Templates'      => 'Email Templates',
        'Log_User_Access'      => 'ข้อมูลการเข้าใช้งาน',
        'SUPERADMIN'           => 'SUPERADMIN',

        'click_here' => 'คลิกที่นี่',

        /*
         * this is for html direction to use in html and css classes like :
         * pull-left , pull-right , text-right ...
         * to make it easy to use the the view for rtl langs .
         * unless your language use right-to-left direction , you should keep it as it is :
         */
        'right'      => 'right',
        'left'       => 'left',

        'all_rights_reserved' => '',
        'copyright'           => '',
        'powered_by'          => '',

        'notification_you_have'     => 'คุณมี',
        'notification_notification' => 'การแจ้งเตือน',
        'notification_new'          => 'มีการแจ้งเตือนใหม่!',

        'login_register_style'                => 'รูปแบบการเข้าสู่ระบบ',
        'email_setting'                       => 'ตั้งค่าอีเมล',
        'application_setting'                 => 'ตั้งค่าโปรแกรม',

        // table filter & sort
        'filter_select_operator_type'         => 'เลือกเงื่อนไข',
        'filter_ascending'                    => 'น้อยไปมาก',
        'filter_descending'                   => 'มากไปน้อย',
        'filter_equal_to'                     => '=  (เท่ากับ)',
        'filter_like'                         => 'มีคำว่า',
        'filter_not_like'                     => 'ไม่มีคำว่า',
        'filter_greater_than_or_equal'        => '>= (มากกว่าเท่ากับ)',
        'filter_less_than_or_equal'           => '<= (น้อยกว่าเท่ากับ)',
        'filter_less_than'                    => '< (น้อยกว่า)',
        'filter_greater_than'                 => '> (มากกว่า)',
        'filter_not_equal_to'                 => '!= (ไม่เท่ากับ)',
        'filter_in'                           => 'อยู่ใน',
        'filter_not_in'                       => 'ไม่อยู่ใน',
        'filter_between'                      => 'ระหว่าง',
        'filter_sort_ascending'               => 'จากน้อยไปมาก',
        'filter_sort_descending'              => 'จากมากไปน้อย',
        'filter_eg'                           => 'เป็นต้น',
        'filter_lorem_ipsum'                  => 'Lorem ipsum',
        'filter_lorem_ipsum_dolor_sit'        => ' Lorem,Ipsum,Dolor Sit',
        'filter_search'                       => 'ค้นหา',
        'filter_from'                         => 'ตั้งแต่',
        'filter_to'                           => 'ถึง',
        'filter_sorting'                      => 'การจัดเรียง',

        // confirmation
        'confirmation_yes'                    => 'ใช่',
        'confirmation_no'                     => 'ไม่ใช่',

        //filemanager
        'chose_an_image'                      => 'เลือกรูปภาพ ',
        'chose_an_file'                       => 'เลือกไฟล์ ',

        //action confirmation
        'confirmation_title'                  => 'ยืนยัน',
        'confirmation_text'                   => 'ยืนยันการทำงาน?',
        'confirmButtonText'                   => 'ยืนยัน',


        // privilege
        'privileges_name'                     => 'ชื่อสิทธิ์',
        'privileges_super_admin'              => 'Super Admin',
        'privileges_standart_user'            => 'Standard user',
        'privileges_ID'                       => 'ID',
        'set_as_superadmin'                   => 'เป็น Super Admin',
        'chose_theme_color_select'            => 'เลือกธีม',
        'chose_theme_color'                   => ' ธีมสี',
        'privileges_configuration'            => 'กำหนดค่าสิทธิ์',
        'privileges_module_list_no'           => 'No.',
        'privileges_module_list_mod_names'    => 'Module\'s Name',
        'privileges_module_list_view'         => 'ดู',
        'privileges_module_list_create'       => 'เพิ่ม',
        'privileges_module_list_read'         => 'อ่าน',
        'privileges_module_list_update'       => 'แก้ไข',
        'privileges_module_list_delete'       => 'ลบ',

        //datamodal
        'datamodal_select'                    => 'เลือก',
        'datamodal_search_and_enter'          => 'เลือก...',
        'datamodal_enter_to_search'           => 'กดปุ่ม Enter เพื่อค้นหา',
        'datamodal_browse_data'               => 'เลือกข้อมูล',
        'datamodal_browse_file'               => 'เลือกไฟล์',


        //child
        'table_detail'                        => 'ตารางข้อมูล',
        'your_file_size_is_too_big'           => 'ไฟล์มีขนาดใหญ่เกินไป',
        'save_changes'                        => 'บันทึก',
        'please_complete_the_form'            => 'กรุณาป้อนข้อมูลให้ครบ!',
        'this_field_is_required'              => 'จำเป็นต้องป้อนข้อมูล',
        'text_form'                           => 'ฟอร์ม',
        "your_file_extension_is_not_allowed " => "ประเภทไฟล์นี้ไม่สามารถใช้งานได้!",
    ];
